In [1]:
import torch
a = torch.arange(9, dtype= torch.float) - 4
b = a.reshape((3, 3))

In [2]:
a

tensor([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [5]:
a.norm(2)

tensor(7.7460)

In [6]:
a.norm(1)

tensor(20.)

In [8]:
import numpy as np
aa = a.numpy()

In [10]:
norma2 = np.sum(aa**2)**0.5
norma2

7.745966692414834

In [15]:
norma1 = np.sum(np.abs(aa))
norma1

20.0

In [25]:
from torch.autograd import Variable
l2_reg = Variable(torch.FloatTensor(1), requires_grad=True)
l2_reg = l2_reg + a.norm(2)

In [26]:
l2_reg.detach().numpy()

array([7.745967], dtype=float32)

In [28]:
l1_reg = Variable(torch.FloatTensor(100), requires_grad=True)
l1_reg = l1_reg + a.norm(2)
l1_reg.detach().numpy()

array([7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.745967, 7.745967, 7.745967, 7.745967,
       7.745967, 7.745967, 7.760085, 7.745967, 7.745967, 7.745